# IMAGEN MODELO
FROM eclipse-temurin:21.0.6_7-jdk

# INFORMAR PUERTO DE EJECUCION DEL CONTENEDOR
EXPOSE 8080

# DEFINIR DIRECTORIO RAIZ DE NUESTRO CONTENEDOR
WORKDIR /root

# COPIA Y PEGAR ARCHIVOS DENTRO DEL CONTENEDOR
COPY ./pom.xml /root
COPY ./.mvn /root/.mvn
COPY ./mvnw /root

# DAR PERMISOS DE EJECUCION AL MVNW
RUN chmod +x mvnw

# DESCARGAR LAS DEPENDENCIAS
RUN ./mvnw dependency:go-offline

# COPIAR EL CODIGO FUENTE DENTRO DEL CONTENEDOR
COPY ./src /root/src

# BUILD PROYECT
RUN ./mvnw clean install -DskipTests

# LEVANTAR APP CUANDO EL CONTENEDOR INICIE
ENTRYPOINT ["java", "-jar", "/root/target/FoodOrderSystem-0.0.1-SNAPSHOT.jar"]
