services:
  order-system-image:
    image: order-system-image
    container_name: order-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres_database
    environment:
      POSTGRES_PASSWORD: 127300
      POSTGRES_DB: "foodOrder"
      POSTGRES_USER: "jvadev"

    ports:
      - "5433:5432"
    networks:
      - spring-network
    volumes:
      - postgres-volume:/var/lib/postgresql/data
networks:
  spring-network:
volumes:
  postgres-volume: